# Generated by Django 5.2.8 on 2025-12-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.CharField(default='Unknown', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.CharField(default='Unknown', max_length=10),
            preserve_default=False,
        ),
    ]
